language: node_js
sudo: false
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: VlI6jpRhROFnM1bBw9NbvbJCWuYn+INj6r/4Wj38+7jzkjNm4LAEasvKVo+QDa5gaQzDHNsuLCiH9Y52vcUVhUIAFqP5nDkXrH2J+ETHKIQalJ/DRQAkS/UcNBbEJPfUyGsagS4hHXWa6bfErYFdspt9d9kXOxuNKBolePCSocw=
